spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: Munyat
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    # hibernate:
    #   ddl-auto: create